import { EVENTOS, EV_CAT_INFO } from '../../features/eventos/data/eventos.data'
import { LOCAL } from '../../shared/lib/images'
import { ES } from '../../shared/i18n/dict_es'
import { EN } from '../../shared/i18n/dict_en'

const H = ES.eventos
const HE = EN.eventos
const imgOf = (v) => (typeof v === 'string' ? v : '')

const CAT_IDS = ['Todos', 'Viajes Misioneros', 'Conferencias', 'Capacitaciones', 'Campamentos']

export const DEFAULT_EVENTOS = {
  hero: {
    pill_es: H.hero.pill, pill_en: HE.hero.pill,
    h1a_es: H.hero.h1a, h1a_en: HE.hero.h1a,
    h1b_es: H.hero.h1b, h1b_en: HE.hero.h1b,
    p_es: H.hero.p, p_en: HE.hero.p,
    s1_es: H.hero.s1, s1_en: HE.hero.s1,
    s2_es: H.hero.s2, s2_en: HE.hero.s2,
    s3_es: H.hero.s3, s3_en: HE.hero.s3,
    s4_es: H.hero.s4, s4_en: HE.hero.s4,
    img: imgOf(LOCAL.inicio4),
    bg: '',
  },
  sec1: { n: H.sec1.n, pill_es: H.sec1.pill, pill_en: HE.sec1.pill, title_es: H.sec1.title, title_en: HE.sec1.title, sub_es: H.sec1.sub, sub_en: HE.sec1.sub },
  sec2: { n: H.sec2.n, pill_es: H.sec2.pill, pill_en: HE.sec2.pill, title_es: H.sec2.title, title_en: HE.sec2.title, sub_es: H.sec2.sub, sub_en: HE.sec2.sub },
  sec3: { n: H.sec3.n, pill_es: H.sec3.pill, pill_en: HE.sec3.pill, title_es: H.sec3.title, title_en: HE.sec3.title, sub_es: H.sec3.sub, sub_en: HE.sec3.sub },
  cats: CAT_IDS.map((id) => ({
    id,
    e: EV_CAT_INFO[id].e,
    d_es: EV_CAT_INFO[id].d, d_en: EV_CAT_INFO[id].d,
    img: imgOf(EV_CAT_INFO[id].img),
  })),
  eventos: EVENTOS.map((e) => ({
    n: e.n, cat: e.cat,
    d_es: e.d, d_en: e.d,
    fecha: e.fecha, hora: e.hora, lugar: e.lugar, mod: e.mod,
    p: e.p, cupos: e.cupos, inscritos: e.inscritos, rating: e.rating,
    tag: e.tag, img: imgOf(e.img),
    programa_es: [...e.programa], programa_en: [...e.programa],
  })),
  bcb: {
    pill_es: '🔥 Intensivo e Integral · 10 Ene — 8 Feb',
    pill_en: '🔥 Intensive & Integral · Jan 10 — Feb 8',
    h2_es: 'BCB Transcultural', h2_en: 'BCB Transcultural',
    p_es: 'Programa de Entrenamiento Misionero en Base, Campo y Bi-vocacional. Dos fases que marcan tu llamado.',
    p_en: 'Missionary Training Program in Base, Field, and Bi-vocational. Two phases that shape your calling.',
    f0_es: 'Base en Cusco', f0_en: 'Base in Cusco',
    f0sub_es: '10 Ene — 8 Feb · 4 sem', f0sub_en: 'Jan 10 — Feb 8 · 4 wks',
    f1_es: 'Campo transcultural', f1_en: 'Transcultural field',
    f1sub_es: '15-20 días · 3 rutas', f1sub_en: '15–20 days · 3 routes',
    k0_es: '1° FASE · 10 ENE — 8 FEB · 4 SEMANAS', k0_en: '1ST PHASE · JAN 10 — FEB 8 · 4 WEEKS',
    k0t_es: 'Entrenamiento en Base', k0t_en: 'Base Training',
    k0p1_es: 'Un mes intensivo, teórico y práctico: cursos, talleres, foros, plenarias, seminarios, conciertos de alabanza, ferias y experiencias transculturales.',
    k0p1_en: 'One intensive month, theory and practice: courses, workshops, forums, plenaries, seminars, worship concerts, fairs, and transcultural experiences.',
    k0p2_es: 'Tiempo desafiante para asumir tu rol en la misión global: descubre tu llamado, entiende el plan de Dios y da pasos concretos mientras adquieres destrezas para servir mejor.',
    k0p2_en: 'A challenging time to take up your role in global mission: discover your calling, understand God’s plan, and take concrete steps while gaining skills to serve better.',
    hAreas_es: 'Áreas de entrenamiento', hAreas_en: 'Training areas',
    hOficios_es: 'Bi-vocacional · 4 oficios', hOficios_en: 'Bi-vocational · 4 trades',
    hIncluye_es: 'Todo incluido', hIncluye_en: 'All included',
    fechaT_es: '📅 Fecha', fechaT_en: '📅 Date',
    fechaV_es: '10 Ene — 8 Feb', fechaV_en: 'Jan 10 — Feb 8',
    lugarT_es: '📍 Lugar', lugarT_en: '📍 Place',
    lugarV_es: 'SEMIT Cusco · Huayllapampa', lugarV_en: 'SEMIT Cusco · Huayllapampa',
    hInv_es: 'Elige tu inversión', hInv_en: 'Choose your investment',
    verMas_es: '¿Solo puedes 1 semana? Ver detalle +', verMas_en: 'Can you only do 1 week? See detail +',
    verMenos_es: 'Ocultar detalle semanal −', verMenos_en: 'Hide weekly detail −',
    inscBase_es: 'Haz clic aquí para inscribirte →', inscBase_en: 'Click here to enroll →',
    k1_es: '2° FASE · 15-20 DÍAS · DENTRO Y FUERA DEL PERÚ', k1_en: '2ND PHASE · 15–20 DAYS · INSIDE AND OUTSIDE PERU',
    k1t_es: 'Entrenamiento en Campo', k1t_en: 'Field Training',
    k1p1_es: 'Planificación, preparación y ejecución de un Viaje Misionero Transcultural. Pondrás en práctica lo aprendido y descubrirás los dones que Dios te dio.',
    k1p1_en: 'Planning, preparation, and execution of a Transcultural Mission Trip. You’ll put into practice what you learned and discover the gifts God gave you.',
    k1p2_es: 'Capacitación práctica en servicio cristiano, eclesiástico y humanitario, en un medio transcultural diferente al tuyo.',
    k1p2_en: 'Hands-on training in Christian, church, and humanitarian service, in a transcultural setting different from your own.',
    hRuta_es: 'Elige tu ruta', hRuta_en: 'Choose your route',
    opc_es: 'Opción', opc_en: 'Option',
    viajas_es: 'viajas con tu equipo, dirigido por dos misioneros de campo.',
    viajas_en: 'you travel with your team, led by two field missionaries.',
    hCubre_es: 'El costo cubre', hCubre_en: 'The cost covers',
    waCampo_es: 'WhatsApp Campo →', waCampo_en: 'WhatsApp Field →',
    waCampoMsg_es: 'Hola SEMIT, quiero info del Campo BCB', waCampoMsg_en: 'Hi SEMIT, I want info about the BCB Field',
    inscCampo_es: 'Inscríbete aquí →', inscCampo_en: 'Enroll here →',
    nota1_es: '👨‍🏫 Entrenadores, profesores y misioneros de campo de amplia experiencia te guiarán en todo el proceso.',
    nota1_en: '👨‍🏫 Trainers, teachers, and field missionaries with broad experience will guide you through the whole process.',
    nota2_es: '🌎 ¡Tendrás la oportunidad de hacer Misiones en Latinoamérica!',
    nota2_en: '🌎 You’ll have the chance to do Missions in Latin America!',
    nota3_es: '👨‍👩‍👧 Familia nuclear: consulta becas y subvenciones.',
    nota3_en: '👨‍👩‍👧 Nuclear family: ask about scholarships and subsidies.',
    nota4_es: '💰 Adelanto S/.300 garantiza vacante. Cancela antes de la promo o hasta el 10 Ene 2026.',
    nota4_en: '💰 S/.300 advance secures your spot. Cancel before the promo or by Jan 10, 2026.',
    nota5_es: '💳 Pago: depósito, transferencia o Yape. Datos al final del formulario.',
    nota5_en: '💳 Payment: deposit, transfer, or Yape. Details at the end of the form.',
    nota6_es: '📅 Costo Semanal S/.250 por 1 semana (lun-dom). Incluye todos los gastos y la salida misionera de la semana elegida. Puedes tomar una o más semanas según tu disposición.',
    nota6_en: '📅 Weekly Cost S/.250 for 1 week (Mon–Sun). Includes all expenses and the mission outing of the chosen week. You can take one or more weeks as you wish.',
    nota7_es: '💲 Costos varían según la ruta elegida. Consulta informes BCB:',
    nota7_en: '💲 Costs vary by chosen route. Ask for BCB info:',
    cubre_es: ['🎫 Pasajes aéreo y/o terrestre', '🏠 Hospedaje en campo', '🍲 Alimentación', '🤝 Coordinaciones locales'],
    cubre_en: ['🎫 Air and/or ground tickets', '🏠 Field lodging', '🍲 Meals', '🤝 Local coordination'],
    img_base: imgOf(LOCAL.inicio2),
    bg: '',
    areas: [
      { e: '📖', t_es: 'Misiones', t_en: 'Misiones', d_es: 'Llamado, estrategia y campo transcultural.', d_en: 'Llamado, estrategia y campo transcultural.', img: imgOf(LOCAL.nosotrosA) },
      { e: '✝️', t_es: 'Biblia', t_en: 'Biblia', d_es: 'Panorama y estudio inductivo aplicado.', d_en: 'Panorama y estudio inductivo aplicado.', img: imgOf(LOCAL.cursosA) },
      { e: '⛪', t_es: 'Teología', t_en: 'Teología', d_es: 'Doctrina sólida para enseñar a otros.', d_en: 'Doctrina sólida para enseñar a otros.', img: imgOf(LOCAL.nosotrosHero) },
      { e: '🛠️', t_es: 'Bi-vocacional', t_en: 'Bi-vocacional', d_es: 'Oficio técnico para sostener tu ministerio.', d_en: 'Oficio técnico para sostener tu ministerio.', img: imgOf(LOCAL.cursosB) },
    ],
    oficios: [
      { e: '🪚', t_es: 'Carpintería', t_en: 'Carpintería', d_es: 'Melamina y madera.', d_en: 'Melamina y madera.', img: imgOf(LOCAL.cursosB) },
      { e: '🍳', t_es: 'Gastronomía', t_en: 'Gastronomía', d_es: 'Alta cocina práctica.', d_en: 'Alta cocina práctica.', img: imgOf(LOCAL.inicio3) },
      { e: '💈', t_es: 'Peluquería', t_en: 'Peluquería', d_es: 'Profesional y rentable.', d_en: 'Profesional y rentable.', img: imgOf(LOCAL.nosotrosB) },
      { e: '🔥', t_es: 'Soldadura', t_en: 'Soldadura', d_es: 'Estructuras metálicas.', d_en: 'Estructuras metálicas.', img: imgOf(LOCAL.cursosHero) },
    ],
    incluye: [
      { e: '🏠', t_es: 'Hospedaje', t_en: 'Hospedaje', d_es: 'En lugar tranquilo.', d_en: 'En lugar tranquilo.', img: imgOf(LOCAL.nosotrosC) },
      { e: '🍲', t_es: 'Alimentación', t_en: 'Alimentación', d_es: 'Adecuada y balanceada.', d_en: 'Adecuada y balanceada.', img: imgOf(LOCAL.inicio4) },
      { e: '📚', t_es: 'Materiales y libros', t_en: 'Materiales y libros', d_es: 'Todo lo necesario.', d_en: 'Todo lo necesario.', img: imgOf(LOCAL.nivelesHero) },
      { e: '✈️', t_es: 'Viajes misioneros', t_en: 'Viajes misioneros', d_es: 'Salidas semanales.', d_en: 'Salidas semanales.', img: imgOf(LOCAL.eventosA) },
    ],
    campos: [
      { t_es: 'Amazonía Peruana', t_en: 'Amazonía Peruana', d_es: 'Selva, ríos y comunidades nativas.', d_en: 'Selva, ríos y comunidades nativas.', img: imgOf(LOCAL.eventosA) },
      { t_es: 'Norte Perú + Ecuador', t_en: 'Norte Perú + Ecuador', d_es: 'Costa, sierra y frontera misionera.', d_en: 'Costa, sierra y frontera misionera.', img: imgOf(LOCAL.eventosB) },
      { t_es: 'Chile + Argentina', t_en: 'Chile + Argentina', d_es: 'Cono sur transcultural urbano.', d_en: 'Cono sur transcultural urbano.', img: imgOf(LOCAL.eventosC) },
    ],
    costos: [
      { tag: 'Oct', p: 'S/.750', n_es: 'Promoción Octubre. Inscríbete en octubre.', n_en: 'Promoción Octubre. Inscríbete en octubre.' },
      { tag: 'Nov', p: 'S/.800', n_es: 'Promoción Noviembre. Inscríbete en noviembre.', n_en: 'Promoción Noviembre. Inscríbete en noviembre.' },
      { tag: 'Dic', p: 'S/.850', n_es: 'Promoción Diciembre. Inscríbete en diciembre.', n_en: 'Promoción Diciembre. Inscríbete en diciembre.' },
      { tag: 'Ene', p: 'S/.880', n_es: 'Costo Regular. Hasta el 10 de enero 2026.', n_en: 'Costo Regular. Hasta el 10 de enero 2026.' },
      { tag: 'Sem', p: 'S/.250', n_es: 'Costo Semanal lun-dom. Incluye gastos y salida misionera.', n_en: 'Costo Semanal lun-dom. Incluye gastos y salida misionera.' },
    ],
  },
  cta: {
    t_es: H.cta.t, t_en: HE.cta.t,
    p1_es: H.cta.p1, p1_en: HE.cta.p1,
    p2_es: H.cta.p2, p2_en: HE.cta.p2,
    p3_es: H.cta.p3, p3_en: HE.cta.p3,
    btn_es: H.cta.btn, btn_en: HE.cta.btn,
  },
  fmt: {},
}

export const EVENTOS_ASSETS = [
  'assets/eventos/semit-4.jpg',
  'assets/eventos/semit-10.jpg',
  'assets/eventos/semit-22.jpg',
  'assets/eventos/semit-23.jpg',
  'assets/inicio/semit-7.jpg',
  'assets/inicio/semit-13.jpg',
  'assets/inicio/semit-14.jpg',
  'assets/inicio/semit-16.jpg',
  'assets/nosotros/semit-1.jpg',
  'assets/nosotros/semit-6.jpg',
  'assets/nosotros/semit-8.jpg',
  'assets/nosotros/semit-9.jpg',
  'assets/niveles/semit-11.jpg',
  'assets/niveles/semit-3.jpg',
  'assets/niveles/semit-5.jpg',
  'assets/cursos/semit-15.jpg',
  'assets/cursos/semit-19.jpg',
  'assets/cursos/semit-21.jpg',
  LOCAL.eventosHero, LOCAL.eventosA, LOCAL.eventosB, LOCAL.eventosC,
  LOCAL.inicio1, LOCAL.inicio2, LOCAL.inicio3, LOCAL.inicio4,
].filter((v, k, a) => v && a.indexOf(v) === k)
