CREATE TABLE IF NOT EXISTS cursos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(160) UNIQUE NOT NULL,
  nombre VARCHAR(255) NOT NULL,
  area VARCHAR(60) NOT NULL,
  descripcion TEXT NOT NULL,
  precio INT NOT NULL DEFAULT 30,
  precio_regular INT NOT NULL DEFAULT 40,
  modalidad VARCHAR(60) NOT NULL DEFAULT 'Virtual',
  nivel VARCHAR(60) NOT NULL DEFAULT 'Fundamentos',
  semanas INT NOT NULL DEFAULT 4,
  lecciones INT NOT NULL DEFAULT 12,
  rating DECIMAL(3,1) NOT NULL DEFAULT 4.9,
  inscritos INT NOT NULL DEFAULT 0,
  tag VARCHAR(160) DEFAULT '',
  imagen_url TEXT,
  activo TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS temario (
  id INT AUTO_INCREMENT PRIMARY KEY,
  curso_id INT NOT NULL,
  orden INT NOT NULL DEFAULT 1,
  titulo TEXT NOT NULL,
  CONSTRAINT fk_temario_curso FOREIGN KEY (curso_id) REFERENCES cursos(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS admin_users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(60) UNIQUE NOT NULL,
  pass_hash TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS admin_sessions (
  token VARCHAR(128) PRIMARY KEY,
  username VARCHAR(60) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
